# Generated by Django 5.1.5 on 2025-01-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
