# Generated by Django 5.1.5 on 2025-01-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_nutrition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RecipeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.nutrition')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='food.recipe')),
            ],
        ),
    ]
