# Generated by Django 5.1.5 on 2025-01-30 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_nutrition_amount_remove_recipe_nutrition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Prep Time (In Minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Prep Time (In Minutes)'),
        ),
    ]
