# Generated by Django 5.1.5 on 2025-01-31 10:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_recipe_cook_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_name', models.CharField(max_length=100)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
