# Generated by Django 5.1.5 on 2025-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sauce Ingredient',
            },
        ),
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='MainDish',
        ),
        migrations.AlterModelOptions(
            name='maindish',
            options={'verbose_name_plural': 'Main Dish Ingredient'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='main_ing',
        ),
        migrations.AddField(
            model_name='recipe',
            name='sauce_ing',
            field=models.ManyToManyField(to='food.sauce'),
        ),
    ]
