# Generated by Django 5.1.5 on 2025-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_sauce_rename_ingredient_maindish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_ing',
            field=models.ManyToManyField(to='food.maindish', verbose_name='For Main dish ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sauce_ing',
            field=models.ManyToManyField(to='food.sauce', verbose_name='For sauce ingredient'),
        ),
    ]
