# Generated by Django 5.1.5 on 2025-02-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_recipe_main_ing_alter_recipe_sauce_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_ing',
            field=models.ManyToManyField(to='food.maindish', verbose_name='For Main Dish Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sauce_ing',
            field=models.ManyToManyField(to='food.sauce', verbose_name='For Sauce Ingredient'),
        ),
    ]
