# Generated by Django 5.1.5 on 2025-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_recipe_like_recipe_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='like_recipe',
        ),
        migrations.AddField(
            model_name='like',
            name='like_recipe',
            field=models.BooleanField(default=False),
        ),
    ]
