# Generated by Django 5.1.5 on 2025-02-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_remove_like_like_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='most_liked',
            field=models.IntegerField(default=0),
        ),
    ]
