# Generated by Django 5.1.5 on 2025-02-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_recipe_most_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='trending',
        ),
    ]
