# Generated by Django 5.1.5 on 2025-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_recipe_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hand_pick',
            field=models.BooleanField(default=False),
        ),
    ]
